index:
    path:     /
    defaults: { _controller: LePetitCoinFrontBundle:Default:index }
    
publier:
    path:     /publier
    defaults: { _controller: LePetitCoinFrontBundle:Publier:publier }
    
annonce:
    path:     /annonce
    defaults: { _controller: LePetitCoinFrontBundle:Annonce:annonce }

